### ISSUE TITLE
[TODO list] Final tasks

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/Animated-drag-and-drop_Younes-Lahouiti#2]
- [ ] Drag and drop on multiple containers
- [ ] Drag hold then scroll wheel 
- [ ] Fix issue on mobile where when the user drags a draggable and holds on top or bottom the swap ain't working properly
